# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b14ab74d37d12a36b7ddc64c21b1d7e4fe22e52f9430efad65581a9c5fe47c4edf528f835013ee966fca13ecd5555a9fa8142be31cac8ee07847641c8a03c7e8

test:
  secret_key_base: 0a7447d9e87639a9c7808759f4f4ebd011b6128e412f23593e7190fad750d73e9815c0e093062b1e3ac43101dc0f823f4ca1e425ecf614e17a2054219be621bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
